# Generated by Django 2.1 on 2018-11-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(blank=True, max_length=64, null=True, verbose_name='主机名')),
                ('ip_address', models.CharField(blank=True, max_length=32, null=True, verbose_name='IP地址')),
                ('application', models.CharField(max_length=64, verbose_name='应用')),
                ('version', models.CharField(max_length=32, verbose_name='服务器型号')),
                ('config', models.CharField(max_length=64, verbose_name='服务器配置')),
                ('location', models.IntegerField(choices=[(0, '世纪互联'), (1, '光环新网'), (2, '亦庄机房'), (3, '阿里云'), (4, 'CDN机房'), (5, '公司内网')], verbose_name='存放地点')),
                ('deadline', models.DateField(max_length=32, verbose_name='过期时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
            ],
        ),
    ]
